.\" Manpage for antimicro.
.\" Contact jeff@jsbackus to correct errors or typos.
.TH ANTIMICRO "1" "05 November 2016" "antimicro 2.23" "User Commands"
.SH NAME
antimicro \- map keyboard keys and mouse controls to a gamepad
.SH SYNOPSIS
.B antimicro
[\fIOPTION\fR] [\fIPROFILE\fR]
.SH DESCRIPTION
.PP
antimicro is a graphical program used to map keyboard keys and mouse controls to a gamepad. This program is useful for playing PC games using a gamepad that do not have any form of built-in gamepad support. However, you can use this program to control any desktop application with a gamepad.
.TP
\fB\-\-tray\fR
launch program in system tray only
.TP
\fB\-\-no\-tray\fR
launch program with the tray menu disabled
.TP
\fB\-h\fR, \fB\-\-help\fR
display this help and exit
.TP
\fB\-v\fR, \fB\-\-version\fR
output version information and exit
.TP
\fB\-\-profile\fR \fI<location>\fR
use specified profile as default for selected controllers. Defaults to all controllers.
.TP
\fB\-\-profile-controller\fR \fI<value>\fR
apply configuration file to a specific controller. <value> can be an controller index, name, or GUID.
.TP
\fB\-\-hidden\fR
launch program without the main window
.TP
\fB\-\-unload\fR \fI[<value>]\fR 
unload currently enabled profile(s). Value can be a controller index, name, or GUID.
.TP
\fB\-\-startSet\fR \fI<number>\fR \fI[<value>]\fR
start joysticks on a specific set. Value can be a controller index, name, or GUID.
.TP
\fB\-\-next\fR
Advance profile loading set options.
.TP
\fB\-d\fR, \fB\-\-daemon\fR
launch program as a daemon.
.TP
\fB\-\-log\-level\fR \fI{debug,info}\fR
Enable logging.
.TP
\fB\-l\fR, \fB\-\-list\fR
Print information about joysticks detected by SDL.
.TP
\fB\-\-map\fR \fI<value>\fR
Open game controller mapping window of selected controller. Value can be a controller index or GUID.
.TP
\fB\-\-eventgen\fR \fI{xtest,uinput}\fR
Choose between using XTest support and uinput support for event generation. Default: xtest.

.SH BUGS
No known bugs.
.SH AUTHOR
Jeff Backus (jeff@jsbackus.com)
Travis Nickles (nickles.travis@gmail.com)

.SH "REPORTING BUGS"
Report dir bugs to antimicro home page: https://github.com/AntiMicro/antimicro
