name: "\U00002753 Question"
description: Questions should be asked ONLY via Discussion module. https://github.com/AntiMicroX/antimicrox/discussions
labels: ["question"]
body:
  - type: checkboxes
    attributes:
      description: Questions should be asked ONLY via Discussion module. https://github.com/AntiMicroX/antimicrox/discussions
      options:
      - label: I am aware that this issue will be closed, because issues are not good place for questions.
        required: true
  - type: textarea
    attributes:
      label: Use discussion module to ask question.
      description: Questions should be asked ONLY via [Discussion](https://github.com/AntiMicroX/antimicrox/discussions) module.
    validations:
      required: false
